# permissions for end users to edit businessservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: businessservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pagerduty-operator
    app.kubernetes.io/part-of: pagerduty-operator
    app.kubernetes.io/managed-by: kustomize
  name: businessservice-editor-role
rules:
- apiGroups:
  - pagerduty.platform.share-now.com
  resources:
  - businessservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pagerduty.platform.share-now.com
  resources:
  - businessservices/status
  verbs:
  - get
