# permissions for end users to view pagerdutyservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pagerdutyservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pagerduty-operator
    app.kubernetes.io/part-of: pagerduty-operator
    app.kubernetes.io/managed-by: kustomize
  name: pagerdutyservice-viewer-role
rules:
- apiGroups:
  - pagerduty.platform.share-now.com
  resources:
  - pagerdutyservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pagerduty.platform.share-now.com
  resources:
  - pagerdutyservices/status
  verbs:
  - get
