//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"gitlab.share-now.com/platform/pagerduty-operator/internal/typeinfo"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicy) DeepCopyInto(out *EscalationPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicy.
func (in *EscalationPolicy) DeepCopy() *EscalationPolicy {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyList) DeepCopyInto(out *EscalationPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EscalationPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyList.
func (in *EscalationPolicyList) DeepCopy() *EscalationPolicyList {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicySpec) DeepCopyInto(out *EscalationPolicySpec) {
	*out = *in
	if in.EscalationRules != nil {
		in, out := &in.EscalationRules, &out.EscalationRules
		*out = make(typeinfo.K8sEscalationRuleList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicySpec.
func (in *EscalationPolicySpec) DeepCopy() *EscalationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicyStatus) DeepCopyInto(out *EscalationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicyStatus.
func (in *EscalationPolicyStatus) DeepCopy() *EscalationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyService) DeepCopyInto(out *PagerdutyService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyService.
func (in *PagerdutyService) DeepCopy() *PagerdutyService {
	if in == nil {
		return nil
	}
	out := new(PagerdutyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagerdutyService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyServiceList) DeepCopyInto(out *PagerdutyServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PagerdutyService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyServiceList.
func (in *PagerdutyServiceList) DeepCopy() *PagerdutyServiceList {
	if in == nil {
		return nil
	}
	out := new(PagerdutyServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PagerdutyServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyServiceSpec) DeepCopyInto(out *PagerdutyServiceSpec) {
	*out = *in
	if in.AutoResolveTimeout != nil {
		in, out := &in.AutoResolveTimeout, &out.AutoResolveTimeout
		*out = new(uint)
		**out = **in
	}
	if in.AcknowledgementTimeout != nil {
		in, out := &in.AcknowledgementTimeout, &out.AcknowledgementTimeout
		*out = new(uint)
		**out = **in
	}
	if in.SupportHours != nil {
		in, out := &in.SupportHours, &out.SupportHours
		*out = (*in).DeepCopy()
	}
	if in.IncidentUrgencyRule != nil {
		in, out := &in.IncidentUrgencyRule, &out.IncidentUrgencyRule
		*out = (*in).DeepCopy()
	}
	if in.ScheduledActions != nil {
		in, out := &in.ScheduledActions, &out.ScheduledActions
		*out = make([]typeinfo.ScheduledAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoPauseNotificationsParameters != nil {
		in, out := &in.AutoPauseNotificationsParameters, &out.AutoPauseNotificationsParameters
		*out = new(typeinfo.K8sAutoPauseNotificationsParameters)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyServiceSpec.
func (in *PagerdutyServiceSpec) DeepCopy() *PagerdutyServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PagerdutyServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerdutyServiceStatus) DeepCopyInto(out *PagerdutyServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerdutyServiceStatus.
func (in *PagerdutyServiceStatus) DeepCopy() *PagerdutyServiceStatus {
	if in == nil {
		return nil
	}
	out := new(PagerdutyServiceStatus)
	in.DeepCopyInto(out)
	return out
}
