package typeinfo

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sSupportHours) DeepCopyInto(out *K8sSupportHours) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]uint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sSupportHours.
func (in *K8sSupportHours) DeepCopy() *K8sSupportHours {
	if in == nil {
		return nil
	}
	out := new(K8sSupportHours)
	in.DeepCopyInto(out)
	return out
}

////////////////////////////////////////////////////////////////////////////////////////

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sIncidentUrgencyRule) DeepCopyInto(out *K8sIncidentUrgencyRule) {
	*out = *in
	if in.DuringSupportHours != nil {
		in, out := &in.DuringSupportHours, &out.DuringSupportHours
		*out = new(K8sIncidentUrgencyType)
		**out = **in
	}
	if in.OutsideSupportHours != nil {
		in, out := &in.OutsideSupportHours, &out.OutsideSupportHours
		*out = new(K8sIncidentUrgencyType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentUrgencyRule.
func (in *K8sIncidentUrgencyRule) DeepCopy() *K8sIncidentUrgencyRule {
	if in == nil {
		return nil
	}
	out := new(K8sIncidentUrgencyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sIncidentUrgencyType) DeepCopyInto(out *K8sIncidentUrgencyType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sIncidentUrgencyType.
func (in *K8sIncidentUrgencyType) DeepCopy() *K8sIncidentUrgencyType {
	if in == nil {
		return nil
	}
	out := new(K8sIncidentUrgencyType)
	in.DeepCopyInto(out)
	return out
}

////////////////////////////////////////////////////////////////////////////////////////

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sInlineModel) DeepCopyInto(out *K8sInlineModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sInlineModel.
func (in *K8sInlineModel) DeepCopy() *K8sInlineModel {
	if in == nil {
		return nil
	}
	out := new(K8sInlineModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduledAction) DeepCopyInto(out *ScheduledAction) {
	*out = *in
	out.At = in.At
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduledAction.
func (in *ScheduledAction) DeepCopy() *ScheduledAction {
	if in == nil {
		return nil
	}
	out := new(ScheduledAction)
	in.DeepCopyInto(out)
	return out
}

////////////////////////////////////////////////////////////////////////////////////////

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertGroupingParameters) DeepCopyInto(out *AlertGroupingParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(K8sAlertGroupParamsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertGroupingParameters.
func (in *AlertGroupingParameters) DeepCopy() *AlertGroupingParameters {
	if in == nil {
		return nil
	}
	out := new(AlertGroupingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAlertGroupParamsConfig) DeepCopyInto(out *K8sAlertGroupParamsConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(uint)
		**out = **in
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAlertGroupParamsConfig.
func (in *K8sAlertGroupParamsConfig) DeepCopy() *K8sAlertGroupParamsConfig {
	if in == nil {
		return nil
	}
	out := new(K8sAlertGroupParamsConfig)
	in.DeepCopyInto(out)
	return out
}
