package typeinfo

////////////////////////////////////////////////////////////////////////////////////////

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertGroupingParameters) DeepCopyInto(out *AlertGroupingParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(K8sAlertGroupParamsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertGroupingParameters.
func (in *AlertGroupingParameters) DeepCopy() *AlertGroupingParameters {
	if in == nil {
		return nil
	}
	out := new(AlertGroupingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sAlertGroupParamsConfig) DeepCopyInto(out *K8sAlertGroupParamsConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(uint)
		**out = **in
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sAlertGroupParamsConfig.
func (in *K8sAlertGroupParamsConfig) DeepCopy() *K8sAlertGroupParamsConfig {
	if in == nil {
		return nil
	}
	out := new(K8sAlertGroupParamsConfig)
	in.DeepCopyInto(out)
	return out
}
